import type { Metadata } from "next";
import "../node_modules/bootstrap-icons/font/bootstrap-icons.css"
import "./globals.css";
import { Navigation } from "@/components/@layout/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Navigation />
        <main className="app w-full max-h-screen overflow-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
